export const lightTheme = {
    body: "#f2f2f2",
    text: "#333",
    toggleBorder: "#FFF",
    background: "#fff",
    tableBackground: "#fff",
    tableText: "#333",
    buttonBackground: "#2c73d2",
    buttonText: "#fff",
    buttonHoverBackground: "#1e5bbd",
    inputBackground: "#fff",
    inputText: "#333",
    labelText: "#333",
    iconEditColor: "blue",
    iconEditHoverColor: "darkblue",
    iconTrashColor: "red",
    iconTrashHoverColor: "darkred",
  };
  
  export const darkTheme = {
    body: "#121212",
    text: "#E0E0E0",
    toggleBorder: "#6B8096",
    background: "#333",
    tableBackground: "#1E1E1E",
    tableText: "#E0E0E0",
    tableHeaderBackground: "#2C2C2C",
    tableShadow: "#000",
    buttonBackground: "#0f1d6f",
    buttonText: "#E0E0E0",
    buttonHoverBackground: "#1e2a8a",
    inputBackground: "#333",
    inputText: "#E0E0E0",
    labelText: "#E0E0E0",
    iconEditColor: "darkblue",
    iconEditHoverColor: "dodgerblue",
    iconTrashColor: "darkred",
    iconTrashHoverColor: "red",
  };
  